// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	response "stock-data-processing/clientsvc/response"

	mock "github.com/stretchr/testify/mock"
)

// ServiceColl is an autogenerated mock type for the ServiceColl type
type ServiceColl struct {
	mock.Mock
}

// GetSummaryByStockCode provides a mock function with given fields: stockCode
func (_m *ServiceColl) GetSummaryByStockCode(stockCode string) response.Response {
	ret := _m.Called(stockCode)

	var r0 response.Response
	if rf, ok := ret.Get(0).(func(string) response.Response); ok {
		r0 = rf(stockCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(response.Response)
		}
	}

	return r0
}

type mockConstructorTestingTNewServiceColl interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceColl creates a new instance of ServiceColl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceColl(t mockConstructorTestingTNewServiceColl) *ServiceColl {
	mock := &ServiceColl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
